language: rust
rust:
  - 1.48.0
cache:
  - cargo
  - directories:
      - "${HOME}/kcov/"
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-kcov || echo "cargo-kcov already installed"
  - cargo kcov --print-install-kcov-sh | sh
script: |
  cargo build --verbose &&
  cargo test --verbose
after_success: |
  cargo kcov --all -v &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
